### ISSUE TITLE
Beeminder But On The Blockchain?

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#22]
Published at https://blog.beeminder.com/blockchain

Beeminder-But-on-the-Blockchain: Decentralization Debate with our Competitor, CommitPool. 

http://doc.bmndr.co/blockchain

(Be sure to mention Betteridge's Law in the hovertext of the image or somewhere.)

https://forum.beeminder.com/t/decentralization-debate-beeminder-but-on-the-blockchain/9743

**Comment by FaireBear** [comment]
![99C07367-9E13-41C9-951D-74427F521C37](https://user-images.githubusercontent.com/7267350/170412208-92e5fe45-e164-4b2f-a145-542d01f73d4a.png)
