### ISSUE TITLE
Beeminder vs CBT (by Nathan Arthur)

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#28]
Published at https://blog.beeminder.com/cbt

http://doc.bmndr.co/cbt

![image](https://user-images.githubusercontent.com/9928/187551799-90175524-72c3-4bd3-a0e0-6ec4b0e92619.png)

## Cognata

* https://forum.beeminder.com/t/beeminder-vs-cbt/7624/26?u=dreev
* https://lorienpsych.com/2021/06/05/depression/

_**Verbata**: psychology, cognitive behavioral therapy, provocative titles, self help, beeminder being a crutch or bandaid,_

**Comment by narthur** [comment]
![Behavior@2x (2)](https://user-images.githubusercontent.com/4655422/189999851-ac195483-e11c-4c0c-a586-4a50ec83126b.png)
![Behavior@2x (1)](https://user-images.githubusercontent.com/4655422/189999858-465b84d0-d7dc-48ba-a5e0-994f70c24e26.png)

**Comment by dreeves** [comment]
![image](https://user-images.githubusercontent.com/9928/190226999-74a6b0ca-16a1-4446-a95a-e95402e31c3c.png)

https://labs.openai.com/s/hts90lVnp2NWPWFBDcyTgbNs
