### ISSUE TITLE
Make posts render correctly for both blog and expost (doc.bmndr.co)

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#290]
I think we have the answer for this already: Don't put the image metadata in the YAML. Beemblog will use the first image in the body if it's not specified in the YAML.

Original gissue:

The previews at, e.g., <http://doc.bmndr.co/athletes> need to render correctly in addition to the blog version at <https://beemblog.onrender.com/athletes>. Currently these seem to be incompatible. If it renders correctly in the doc.bmndr.co version then it has the image twice in the beemblog version. Possibly the answer is to change my expost renderer but we'll need to coordinate on how that should work.

_**Verbata**: render markdown, markdown rendering, expost, etherpad, blog previews,_
```[tasklist]
### Tasks
- [ ] Remove frontmatter image support
```

**Comment by dreeves** [comment]
Philosophical side point: Can we / should we [anti-postel](https://blog.beeminder.com/postel "AKA the Anti-Robustness Principle") this and give an error if you try to specify a title image in the YAML? It probably doesn't matter much but maybe there's less tech debt if we throw away the code that parses image data from the YAML and just say there's One Way To Do It now: Grab the first image in the body.

**Comment by narthur** [comment]
@dreeves I've removed the ability to add an image in the frontmatter.
