### ISSUE TITLE
Image hosting: replicate existing wordpress image hotlinks

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#294]
```[tasklist]
### Desiderata
- [x] Download all the images?
- [x] Either replicate the wp-content/uploads/blahblah paths or set up permanent redirects
```

Image hosting work for the old blog posts: Like the ontology post hotlinks to https://blog.beeminder.com/wp-content/uploads/2022/11/tmp1451.png and if i change that "blog.beeminder.com" to "beemblog.onrender.com" it 404s. 

That means all the images would break if we launched today.

_**Verbata**: mendoza, broken images, hotlinked images, wordpress migration,_

**Comment by narthur** [comment]
@dreeves Do you know how you want to upload new blog images after we deploy? Will you be doing it via gissues?

**Comment by dreeves** [comment]
Via gissues is fine with me!

**Comment by narthur** [comment]
WordPress image uploads have been added to the new blog:

https://blog.beeminder.com/wp-content/uploads/2023/05/mathboardwithbee.png
