### ISSUE TITLE
Changing status to "publish" and hitting Manual Deploy doesn't make the post appear?

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#295]
We may need to close this as cnr since it ended up working but in case it replicates:

I set status=publish in the metadata for /athletes and hit Manual Deploy in render.com but the /athletes post is not showing up at beemblog.onrender.com

_**Verbata**: deploy infrastructure, frontmatter, metadata,_

**Comment by dreeves** [comment]
From Slack:

> filesystem cache is now disabled during deploy

Ohhh, does this explain the problem?

**Comment by narthur** [comment]
@dreeves Yes, I think there were two issues that may have caused this. One was the caching that was accidentally being done during deploy which I've now disabled. The other was that you had put some text before the frontmatter, which I don't think works. Any notes would need to be place between the frontmatter and beginmagic.

I'm going to close this for now. Of course feel free to re-open if you run into this again.

**Comment by dreeves** [comment]
For the last post it still seemed slow to pick up the newly published post. Seemed to take multiple hard refreshes / page reloads before it showed up. That may just be Chrome's fault and there's nothing else to do here.
