### ISSUE TITLE
Lost the cute bee-emoji bullet points

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#296]
Compare:

* https://blog.beeminder.com/datasmithing/
* https://beemblog.onrender.com/datasmithing

_**Verbata**: custom css, beeminder blog idiosyncrasies,_

**Comment by narthur** [comment]
Fixed

<img width="910" alt="Screenshot 2023-08-13 at 12 33 16 PM" src="https://github.com/beeminder/blog/assets/4655422/90492b29-924d-432e-8c27-83c973a73dcc">
