### ISSUE TITLE
Font too small for <ol> and <ul> lists

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#297]
## Replicata

1. Find a blog post with a bulleted or numbered list, eg https://beemblog.onrender.com/athletes

## Expectata

Consistent body font size

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/e9c4a462-d05c-4609-8381-766e02967692)

_**Verbata**: css bugs, mendoza,_

**Comment by narthur** [comment]
Fixed

![image](https://github.com/beeminder/blog/assets/4655422/e548f41f-1054-44f9-b0dc-20d8864daff1)
