### ISSUE TITLE
Tweaks for the 404 page

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#299]
```[tasklist]
### Desiderata
- [x] Change "Page not found" to "404: Page not found"
- [x] Change the links to also show the URLs
```

![image](https://github.com/beeminder/blog/assets/9928/52761e7b-1718-414a-b3cd-ec67e1398796)

_**Verbata**: 404 pages, microcopy,_

**Comment by dreeves** [comment]
If you point me in the right direction, I could make a PR for these tweaks. This is definitely outside the scope of the migration! And it's already such a big improvement over WordPress's dumb anti-magic violation. Thank you!

**Comment by narthur** [comment]
@dreeves Sure thing! Here's the 404 page:

https://github.com/beeminder/blog/blob/master/src/pages/404.astro

The JS between the two `---`'s is build-time JS. The JS in the `<script>` tag is client JS. I'm using client JS to populate the 404 page matches list to avoid complicating / slowing down the build.

**Comment by dreeves** [comment]
After:

![image](https://github.com/beeminder/blog/assets/9928/91df444e-2385-44b5-a7f6-b11ac47e8b9a)
