### ISSUE TITLE
Stop constraining image aspect ratios

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#300]
```[tasklist]
### Desiderata
- [x] Fix original problem with bad cropping
- [ ] Fix new problem with squishing (see link to forum post)
```

narthur says, "I think I need to stop constraining image aspect ratios. Images are getting cropped unattractively on list pages."

![image](https://github.com/beeminder/blog/assets/9928/3225044f-b1f4-4523-85f3-1e884f363cce)

## Cognata

* https://forum.beeminder.com/t/shiny-new-blog-redesign/11107/5?u=dreev
* #306

_**Verbata**: image cropping, image dimensions, mendoza,_

**Comment by narthur** [comment]
This task is complete.

![Screenshot 2023-08-11 at 11 26 32 AM](https://github.com/beeminder/blog/assets/4655422/263f0822-ab3b-499a-bf8f-595632bfbcd7)

**Comment by dreeves** [comment]
Looks good to me now:

![image](https://github.com/beeminder/blog/assets/9928/12c035d1-87e0-48a8-87a3-4c24fc4557d1)
