### ISSUE TITLE
Tags at bottom of post should be separated

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#301]
```[tasklist]
### Desiderata
- [ ] Propose something: vertical whitespace, italics, divider, ...
- [ ] TBD
```

![image](https://github.com/beeminder/blog/assets/9928/a8e39e7a-83a8-4b0b-a323-be02f9f8b430)

**Comment by dreeves** [comment]
I guess in wordpress they're shown in a smaller font.

**Comment by dreeves** [comment]
It actually looks fine in some cases, like this one: https://beemblog.onrender.com/staircase (maybe it still wants italics regardless?)

But it looks ok in that case because we added other "endmatter" like the image credit and the tags fit in with that well.

On other posts it runs into the body text too much.

**Comment by narthur** [comment]
I'm  interpreting this as visually separated. Let me know if I've assumed incorrectly.

**Comment by narthur** [comment]
Fixed

<img width="951" alt="Screenshot 2023-08-13 at 12 23 30 PM" src="https://github.com/beeminder/blog/assets/4655422/3026d428-c12d-4141-8af1-26c1a2b5ee39">
