### ISSUE TITLE
Unicode bug on 404 page

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#302]
Seeing this:

![image](https://github.com/beeminder/blog/assets/9928/3d8cff7e-ff7a-4fa1-a13a-f31a34cd9275)

Instead of this:

![image](https://github.com/beeminder/blog/assets/9928/003a3bb4-14ae-453f-9aec-db0e4c392a8c)

_**Verbata**: displaying weird characters, unicode,_

**Comment by narthur** [comment]
Fixed

<img width="328" alt="Screenshot 2023-08-11 at 11 35 01 AM" src="https://github.com/beeminder/blog/assets/4655422/f7702f4c-73c4-4c38-b971-af3fb9dde435">
