### ISSUE TITLE
How to handle very tall images in list thumbnails?

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#308]
```[tasklist]
### Desiderata
- [ ] Decide what it should do in theory
- [ ] Decide what it should do in practice
- [ ] Do that
```

@dreeves @bsoule How should we handle posts in list pages when the post image is extremely tall and narrow?

<img width="1792" alt="Screenshot 2023-08-13 at 5 10 43 PM" src="https://github.com/beeminder/blog/assets/4655422/3a805dd8-f0b3-4f43-8e38-1151107cc625">

_**Verbata**: image cropping, image sizing, image clipping, square images, images in list view,_

**Comment by dreeves** [comment]
Looks like the wordpress version clips it:

![image](https://github.com/beeminder/blog/assets/9928/e2d4a40c-64e5-47a6-ade3-9d2543c5b411)

I don't have a strong opinion about this myself.

**Comment by narthur** [comment]
Fixed. Now thumbnails are constrained to 200px in height, without distortion.

<img width="736" alt="Screenshot 2023-08-15 at 9 52 55 AM" src="https://github.com/beeminder/blog/assets/4655422/bb519ee7-f9f4-4b87-a63e-9f6b4c4e8a6f">
