### ISSUE TITLE
H3 headers too small

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#310]
Compare wordpress:

![image](https://github.com/beeminder/blog/assets/9928/f235849e-0ddf-42a2-81ba-3f297b1175bb)

To beemblog:

![image](https://github.com/beeminder/blog/assets/9928/a034f5fe-91b2-4274-98bf-04a0993d5386)

The beemblog version almost looks like it's just a normal bolded sentence instead of a subheader.

I'm not sure yet about H4 headers.

_**Verbata**: css, header sizes, font sizing, typography, mendoza,_

**Comment by narthur** [comment]
Fixed

<img width="517" alt="Screenshot 2023-08-15 at 9 48 58 AM" src="https://github.com/beeminder/blog/assets/4655422/ddac856c-57bb-4164-aad2-11eafb2e9a6d">
