### ISSUE TITLE
Deploy v0 to Render.com

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#311]
```[tasklist]
### Desiderata
- [x] Back up the wpengine wp site and db
- [x] Deploy Render blueprint to the Beeminder Render.com org account
- [x] Delete the old static site from Danny's personal Render.com account
- [x] Configure the blog.beeminder.com subdomain to point to the new Render static site
- [x] Protect the github master branch to require PRs going forward
- [x] Cancel wpengine subscription
- [x] Schedule contract review conversation
- [x] Give Danny & Bethany the secret deploy trigger URL
```

Pushing the big red button and being done with WP Engine!

_**Verbata**: deploy, hosting on render.com,_

**Comment by dreeves** [comment]
Nervous face:

![image](https://github.com/beeminder/blog/assets/9928/4c702ee3-7467-4bf7-af6f-370130bbd3df)

**Comment by narthur** [comment]
Beeminder org blueprint deployed: https://beemblog-rble.onrender.com/

**Comment by narthur** [comment]
Old static site deleted from Danny's personal Render account

**Comment by dreeves** [comment]
What are the pros/cons of protecting master? Like lower probability of shooting ourselves in the foot at the cost of some convenience when making quick changes?

**Comment by narthur** [comment]
@dreeves That's correct. Requiring PRs gives us a chance to see any checks that are failing before we deploy to production. We also get Render.com branch previews which are automatically added as comments on PRs, so we can test the site in a production-like environment before it's deployed to production.

**Comment by narthur** [comment]
This is done.
