### ISSUE TITLE
Raw HTML in blurbs

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#312]
```[tasklist]
### Desiderata
- [ ] Decide whether to fix this automatically or manually
- [ ] Confirm no more instances of ugly html in the blurbs
```

## Replicata 

1. Go to https://blog.beeminder.com/2012 and look at the blurbs

## Expectata

Readable blurbs.

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/679602df-d582-4a8d-9162-d03bbf495faf)

_**Verbata**: raw html, excerpts,_

**Comment by dreeves** [comment]
Yes, in the future we should provide explicit blurbs that don't have html and then this question would be moot. But we still have to de-uglify these old ones somehow.

**Comment by narthur** [comment]
Ok. I'm taking that to mean stripping old custom excerpts.

**Comment by narthur** [comment]
Fixed:

<img width="1006" alt="Screenshot 2023-08-15 at 4 16 50 PM" src="https://github.com/beeminder/blog/assets/4655422/6698a8af-0af4-4e9f-bdc0-47d2a73d5073">
