### ISSUE TITLE
Em dashes aren't emmy

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#314]
```[tasklist]
### Desiderata
- [ ] Make the presumably one-character change in the script?
```

bad: –
good: —

Or they could be rendered as html: `&mdash;`

_**Verbata**: mendoza, typography,_

**Comment by narthur** [comment]
Test URL: https://blog.beeminder.com/allitimentation

**Comment by narthur** [comment]
Ok. I've submitted a PR to the Marked plugin we're using to allow us to fix this:

https://github.com/markedjs/marked-smartypants/pull/75

If they don't accept the PR quickly, we can use my fork until they do.

**Comment by dreeves** [comment]
Do you know how/why we got the correct em dashes in the wordpress version? I'm thinking my expost php script was handling it?
