### ISSUE TITLE
How to quickly find the source document from a blog page

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#318]
```[tasklist]
### Desiderata
- [x] Narthur opines on dreev's proposal
- [x] Discuss the idea of combining wp-posts.csv and sources.txt
- [x] NIX: Modify everything below if we _don't_ go with dreev's proposal
- [x] Populate sources.txt with the slugs
- [x] Refactor: sources.txt -> sources.csv (actually posts.json)
- [ ] https://github.com/beeminder/blog/issues/379
```

The source doc's URL doesn't always match the blog post's slug. In wordpress I could click "edit this post" in the header (if logged in to wordpress) and see the source doc. Now I don't have a good way to do that. Any ideas?

## Cognata

* #317

_**Verbata**: deploys, editing existing posts, updating posts, linking posts to their source docs,_

**Comment by dreeves** [comment]
Here's one idea: make sources.txt be like this:

```csv
SLUG,          SOURCE_DOC
akrasia,       doc.bmndr.co/beemblog-akrasia
easyhard,      doc.bmndr.co/beemblog-easyhard
preeat,        doc.bmndr.co/beemblog-preeat
foodhabits,    doc.bmndr.co/foodrules
lildeb,        doc.bmndr.co/lildeb
gym,           doc.bmndr.co/gym
[...]
ontologies,    doc.bmndr.co/ontologies
athletes,      doc.bmndr.co/athletes
blogmorphosis, doc.bmndr.co/blogmorphosis
```

Hmm, I might immediately love it?

**Comment by dreeves** [comment]
And if that makes sense to do then maaaayyybe does it make sense to actually combine wp-posts.csv and sources.csv?

The idea would be that sources.csv gives at least the slug and the source doc URL and optionally it can specify any of the rest of the metadata/frontmatter. For every required metadata field we fail loudly if it's not in sources.csv or at the top of source doc. (If it's in both places and doesn't match, fail loudly.)

Possibly even better than the above would be to suck it up and add the frontmatter to every source doc. Full consistency of past, present, and future! But I don't know how to automate that with etherpad and it would be tedious to do manually.

One baby step in that direction could be to use the same syntax in sources.txt as in the frontmatter in source docs:

```
---
slug: foo
source: doc.bmndr.co/foo
title: The Title of the First Post
date: 2021-01-01
author: dreeves
tags: [tag1, tag2]
status: publish # publish or draft or pending
disqus_id: any-unique-string
excerpt: >
  The excerpt is used for the post preview on the blog index page.
  It can be multiple lines long.
  All HTML and markdown will be stripped.
---
slug: bar
source: doc.bmndr.co/bar
title: The Title of the Next Post
date: 2021-01-01
[...]
---
slug: baz
source: doc.bmndr.co/bar
[etc]
---
```

For new posts that only need slug and source, we could compact to one line each like so:
```
--- slug: qux, source: doc.bmndr.co/qux ---
--- slug: quz, source: doc.bmndr.co/quz ---
```

Except that's weird and fussy so now I kind of want sources.txt to just be JSON!

```json
[{
"slug": "foo",
"source": "doc.bmndr.co/foo",
"title": "The Title of the First Post",
"date": "2021-01-01",
"author": "dreeves",
"tags": ["tag1", "tag2"],
"status": "publish", # publish or draft or pending
"disqus_id": "any-unique-string",
"excerpt": "The excerpt is used for the post preview on the blog index page. It can be multiple lines long. All HTML and markdown will be stripped.",
}, {
"slug": "bar",
"source": "doc.bmndr.co/bar",
"title": "The Title of the Next Post",
"date": "2021-01-01",
[...]
}, {
"slug": "baz",
"source": "doc.bmndr.co/bar",
},
{"slug": "qux", "source": "doc.bmndr.co/qux"},
{"slug": "quz", "source": "doc.bmndr.co/quz"},
]
```

**Comment by narthur** [comment]
@dreeves Is this done now that #372 is done?

**Comment by dreeves** [comment]
One desideratum left. But maybe let's talk about killing the YAML? I kind of hate YAML and also don't like the inconsistency. Maybe we should just put all the metadata in posts.json? I don't know. I'm torn. Having the metadata at the top of the source docs makes a ton of sense.

**Comment by narthur** [comment]
@dreeves Remember that we can easily switch the frontmatter to json format, if it's the yaml format that's making this feel yucky.

**Comment by dreeves** [comment]
Maybe! I have an aesthetic preference for JSON over YAML but that's not critical. The new desideratum about failing loudly if things in posts.json and the frontmatter contradict each other is the actual bug to fix at this point. Lemme make that it's own gissue so we can close this one and then optionally make new gissues for JSON-vs-YAML and for everything-in-posts.json vs use-frontmatter-in-source-docs. [and done]
