### ISSUE TITLE
Migration from WordPress and the blog's new tech stack

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#320]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Secretpreview link
- [x] Keywords/tags
- [x] Title image
- [x] Publish
- [x] Blog blurbs on Beeminder front page
- [x] Waggledance
- [x] Tweet
```

Sequel to #360 

This is narthur's X-Treme Nerd version.

_**Verbata**: tech posts, technology stack, death to wordpress, blog technology, static hosting, CMS,_

**Comment by narthur** [comment]
@dreeves Open to the blog post idea 👍

**Comment by dreeves** [comment]
<img width="957" alt="image" src="https://github.com/beeminder/blog/assets/9928/364c4b05-ed9b-43e4-8f33-1363dfdfe0b5">

**Comment by bsoule** [comment]
<img width="724" alt="Screen Shot 2023-08-18 at 15 13 23" src="https://github.com/beeminder/blog/assets/46881/fc48a804-9ee1-426b-9336-7c6e7c06f90a">

**Comment by narthur** [comment]
@dreeves When is the deadline for this post?

**Comment by narthur** [comment]
Tech stack brain dump:

- static site
- astro
- zod for data schemas, transformations
- typescript, js, node, pnpm
- hosted on render.com (blueprints)
- perf, security
- design refresh, aiming to be more inline with main site
- etherpad workflow
- link prefetching
- markdown augmentations
- vite, vitest
- 404 page (levenshtein)
- fontsource
- happy-dom
- build optimizations (memoization, happy-dom, p-limit, etc)
- eslint, prettier

**Comment by narthur** [comment]
<img width="436" alt="Screenshot 2023-09-06 at 10 04 44 AM" src="https://github.com/beeminder/blog/assets/4655422/2f985f24-1b03-436f-a683-160589d98333">
<img width="240" alt="Screenshot 2023-09-06 at 9 29 05 AM" src="https://github.com/beeminder/blog/assets/4655422/a882668a-2fdb-4bed-8ad5-4d76832fa948">
<img width="439" alt="Screenshot 2023-09-06 at 9 26 52 AM" src="https://github.com/beeminder/blog/assets/4655422/f7f05af8-aaea-4fa9-98dc-9884e01b7b06">

**Comment by bsoule** [comment]
image idea / suggestion:
![bethany4036_an_illustration_of_a_complex_upgrade](https://github.com/beeminder/blog/assets/46881/5bcb4d04-f5db-4c4e-bff3-a92f589e3d29)
