### ISSUE TITLE
Clean up legacy URL cruft

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#321]
```[tasklist]
### Desiderata
- [x] Narthur reviews remaining instances of "dtherpad" in the code
```

There was some legacy stuff for unusual source URLs:

https://github.com/search?q=repo%3Abeeminder%2Fblog%20dtherpad&type=code

But we're cleaning up those inconsistencies so that should be unnecessary now.

## Cognata

* #317
* #319 

_**Verbata**: refactoring, cruft cleanup, anti-postel,_

**Comment by narthur** [comment]
@dreeves Is this done now?

**Comment by dreeves** [comment]
Oh, wait, not quite. Some stuff in [src/lib/getPosts.spec.ts](https://github.com/beeminder/blog/blob/146241366f0b126749fbd4401a3cb1b9b6c0a7bf/src/lib/getPosts.spec.ts#L37).

**Comment by narthur** [comment]
@dreeves I've removed the remaining references to dtherpad. Can we go ahead and close this issue?
