### ISSUE TITLE
Future-proof the source URLs / canonicalize

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#322]
```[tasklist]
### Desiderata
- [x] Fix the typo in the source doc URL in wp-posts.csv that was causing things to break
- [x] Check that it works to put non-canonical source URLs in sources.txt -- do they get properly canonicalized and matched to wp-posts.csv?
```

So I broke things with #317 and #319 and I'm working on cleaning up my mess.

I think the key is canonicalizing the source URLs.

A nice future-proof way to do this is for the canonical source URLs to be the thing you can actual do the fetchURL on to get the markdown source of the blog post. In our case that's like `https://ether.pad/foo/export/txt`.

We don't want to have to type that version every time so we want a canonicalize function to turn something like `ether.pad/foo` into `https://ether.pad/foo/export/txt`.

In the future if we're using something other than etherpad -- maybe we put the source files for the blog posts directly in GitHub -- then we can just specify the raw URL and everything still works.

For example, we don't want to unconditionally append `/export/txt` to the end of the URL before fetching. That's specific to the current etherpad setup. Instead we want, well, like I said above. To canonicalize. So the etherpad URLs work and so does any future scheme.

UPDATE / CONCLUSION ON BREAKING THINGS IN #317 and #319:

The canonicalization bug was that, as part of manually canonicalizing the source doc URLs in the wordpress legacy datafile (wp-posts.csv) I mangled one of them. That yielded a semi-silent failure: since it couldn't fetch the source doc it treated it as a new post and complained that it didn't have an explicit excerpt in the metadata/frontmatter. It should've complained specifically about the failure to fetch the source doc. Most of my changes trying to "clean up my mess" were a wild goose chase thinking I'd done the canonicalizing wrong.

## Cognata

* #321 
* #317 
* #319 

_**Verbata**: refactoring, future-proofing,_

**Comment by dreeves** [comment]
I think this is all set, @narthur. I'll let you review and close if you agree!

**Comment by narthur** [comment]
Seems good to me!
