### ISSUE TITLE
Fix support for comments on non-wp posts

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#327]
```[tasklist]
### Desiderata
- [x] Add required frontmatter property for `disqusID` for pointing to the Disqus comments
- [x] Fail if `disqusID` missing or not unique
- [x] Fail if `slug` missing or not unique
- [ ] https://github.com/beeminder/blog/issues/370
- [ ] https://github.com/beeminder/blog/issues/372
```

According to this code I don't think I've accounted for comments on new posts that don't have legacy wordpress data:

https://github.com/beeminder/blog/blob/7f309fe102b34b75f0a594a0cb97230d9435cb30/src/schemas/post.ts#L48-L51

That needs to be fixed before we publish any new posts.

## Cognata

* https://github.com/beeminder/beeminder/issues/3104

_**Verbata**: mendoza, Disqus comments IDs,_

**Comment by narthur** [comment]
@dreeves How should we fix this? If we rely on the post's slug, then correcting the slug (say if there's a typo) would reset the comments for the post. Could we rely on the etherpad slug instead? That would result in someone who know how it worked to be able to find every etherpad post...

**Comment by dreeves** [comment]
Uh oh, I guess we better hurry and figure this out! I don't want to rely on the etherpad slugs.
Can we enforce never changing the blog's URL? Or, like, whatever the original URL is, that's the permanent identifier for the Disqus comments?

**Comment by narthur** [comment]
@dreeves Hmm. I don't think we have a good way to store the original URL. What if we just require a frontmatter ID for new posts?

**Comment by dreeves** [comment]
Requiring a unique ID in the metadata sounds fine, as long as we fail loudly if it's missing or not actually unique.

(In general I'd love to get more assertions in the code and generally be pretty dogmatic about [anti-postel](https://blog.beeminder.com/postel "I sure am pleased by how, if I had accidentally typed this URL as the plausible 'blog.bmndr.co/antipostel' instead of 'blog.bmndr.co/postel' that the 404 page would've helpfully suggested what I meant, with no anti-magic violation!") so that everything breaks immediately when things aren't exactly as expected. Like trying to be forgiving about a missing or colliding ID for Disqus comments could lead to a real mess, I'd imagine.)

**Comment by dreeves** [comment]
But thinking more: we already have "slug" aka the URL slug which is also a unique ID, right? Other questions:

1. Can we change the URL slug?
2. If so, how do we do legacy redirects?
3. What happens if we accidentally specify a URL slug in the metadata that's already taken?

**Comment by narthur** [comment]
@dreeves Currently I don't think there's any checks on slug uniqueness. You could change a slug and it would work fine. No redirects though. I would suggest having a second frontmatter property, something like redirects, if we want to have the ability to redirect old slugs to the current slug.

**Comment by narthur** [comment]
@dreeves What do you think of the task list I've added above?

**Comment by narthur** [comment]
I'm ok with using the slug as an id, I can just imagine that there might be a reason at some point to modify a slug, say for a typo or because you no longer want to use a term, like `road`.

**Comment by dreeves** [comment]
Live chat ensued and desiderata now seem solid! I was hung up on having to redundantly specify "slug: foo, disqusID: foo" every time but the answer is: so be it. We need to explicitly point to the Disqus ID. If we end up switching to Discourse then that explicitness will be especially valuable. "These old posts have Disqus comments / these new posts have Discourse comments." Also it's what minimizes the amount of code to write!

**Comment by narthur** [comment]
Resolved with #335.

@dreeves Note the new property is called `disqus_id` and not `disqusID`.

**Comment by dreeves** [comment]
Note remaining desiderata.

**Comment by dreeves** [comment]
Redirects is now gissue #370. 

Do all existing posts, both pre- and post-wordpress, have an explicit disqus ID specified now?

**Comment by narthur** [comment]
@dreeves No. I'm thinking it makes sense to change that as part of the Unified Json change.
