### ISSUE TITLE
More aggressive cache-busting when deploying?

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#330]
Workaround: do a hard refresh of the page after the deploy finishes.
(When in doubt, try in Firefox, which is less stupidly aggressive about caching than Chrome.)

## Cognata

* #292 

_**Verbata**: deploys, reloading the page after deploying,_

**Comment by narthur** [comment]
My preference would be to do nothing here, as the fact that a hard-refresh fixes this makes me think it's either a browser cache issue, or a render.com delay.
