### ISSUE TITLE
Mangled blurb for Complice post on 404 page

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#338]
```[tasklist]
### Desiderata
- [ ] Diagnose it
- [ ] Fix it or work around it
```

## Replicata 

1. Surf to https://blog.beeminder.com/complic
2. Look at the link to the intended post, blog.beeminder.com/complice (with the e on the end)

## Expectata

A normal link with the URL and title

## Resultata

This mess:

![image](https://github.com/beeminder/blog/assets/9928/83444688-7c04-40b7-a6ea-85db0904cd3a)

## Nota Nebulosa

Presumedly we can work around this by putting an explicit blurb in the post's metadata? But we should diagnose how this happened in case there are other instances.

_**Verbata**: broken html, Fancy 404s,_

**Comment by dreeves** [comment]
Another instance: https://blog.beeminder.com/rssfeed

**Comment by dreeves** [comment]
Oh ho, this fixed itself! Maybe this was related to the regression from this morning where we weren't sanitizing the fetched content, ie, ignoring the begin/end magic.

**Comment by narthur** [comment]
@dreeves Yes! That's my guess too. Closing as CNR.
