### ISSUE TITLE
Remove unused levenshtein dependency

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#342]
```[tasklist]
### Desiderata
- [x] Remove levenshtein from package.json
- [x] Narthur confirms that's all there is to do?
```

It appears that the levenshtein pnpm dependency is unused. We should remove it if so.

_**Verbata**: dependency management, infra cleanup, clearing clutter,_

**Comment by dreeves** [comment]
Affirmative! That was from me beating my head against the dev-vs-prod differences in putting together the Fancy 404 functionality. Turns out it works great to do it all client-side.

**Comment by narthur** [comment]
This is done

**Comment by narthur** [comment]
@dreeves Can we close now?

**Comment by dreeves** [comment]
Yeah, by opener-closes you don't have to wait for me to confirm when it's your own gissue. See #303
