### ISSUE TITLE
Redirect old feed URL

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#343]
```[tasklist]
### Desiderata
- [ ] Decide the canonical URL for the RSS feed
- [ ] Do the 301 redirect
- [ ] Add other common aliases: /feed, /rss, /feed.xml, /rss.xml
- [ ] Do we have to care trailing slashes, like about "/feed" vs "/feed/"?
```

HT zzq: https://forum.beeminder.com/t/shiny-new-blog-redesign/11107/2?u=dreev

_**Verbata**: legacy redirects, rss feed, URLs,_

**Comment by narthur** [comment]
@dreeves I thought previously people subscribed via feedburner. Is that not the case?

**Comment by dreeves** [comment]
Oh, yes. Wanna clarify with zzq in the forum thread?

**Comment by narthur** [comment]
@dreeves Meh. It's true that WordPress uses /feed by default, so it doesn't hurt to add a redirect for that, since it would have worked previously.

**Comment by narthur** [comment]
feed, rss, and rss.xml now redirect to feed.xml. Also looks like trailing slashes are handled properly, too, at least in Arc. @dreeves let me know if you want to change your mind on the canonical RSS path.
