### ISSUE TITLE
Upgrade Python

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#344]
```[tasklist]
### Desiderata
- [x] Narthur opines on whether this sounds worth it or what we're even using Python for
```

I spotted this in the Render console:

> Using Python version 3.7.10 (default)

Apparently that version is end-of-lifed [https://devguide.python.org/versions/] and I hear Python 3.11 is much faster so maybe that's worth upgrading?

_**Verbata**: infrastructure upgrades, python versions,_

**Comment by narthur** [comment]
@dreeves We're not intentionally using python. I think this is just a part of Render's standard build env for some reason. All we're using directly is Node.
