### ISSUE TITLE
Fail eagerly in case of etherpad fetching problems

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#346]
```[tasklist]
### Desiderata
- [x] Add error checking for the begin/end magic
- [ ] Anything even more restrictive we can do? Lack of any script tags in the rendered html?
```

sanity check: if the build process on render couldn't reach etherpad or etherpad returned garbage somehow, would the whole blog break?

we think the answer is that the build would fail and the previous deploy would remain the live one.

but let's make sure!

## Cognata

* #331 

_**Verbata**: mendoza, not breaking the whole blog, error checking,_

**Comment by dreeves** [comment]
what if etherpad returns 200 responses with something other than the actual source docs. like our etherpad server gets hacked and returns spam or something. maybe we need to fail if we don't see the begin/end magic strings?

**Comment by dreeves** [comment]
on reflection, i think it's important to break the build if any source doc doesn't have both the begin/end magic strings. both begin and end because maybe the transmission got interrupted (or the etherpad database corrupted or godknowswhat) and we're not getting the whole document. we really, really don't want to complete the deploy if any of the source docs aren't fully fetched. and there's a pretty long list of ways that could fail -- and we're doing hundreds of fetches on every deploy -- so it's pretty important to ensure the build fails if any of those things happen. checking for begin/end magic covers most of those cases in one fell swoop.

**Comment by dreeves** [comment]
this is a nice invocation of [anti-postel](https://blog.beeminder.com/postel "Anti-Robustness Principle"): be as restrictive as we can be in terms of the format we expect for the source doc.

**Comment by narthur** [comment]
@dreeves This is done and deployed.
