### ISSUE TITLE
Vet strickvl's PR: spellchecking and image optimization

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#348]
```[tasklist]
### Desiderata
- [x] Danny mostly blindly merges PR 😬 cuz strickvl is highly trusted
- [ ] Narthur or strickvl explain what it's doing (eg, where do we see the results of the spellchecking?)
- [ ] TBD
```

## Cognata

* #345 (THE PR IN QUESTION)
* #313

_**Verbata**: spellcheck, large images,_

**Comment by dreeves** [comment]
I've gotten multiple reports that the images are way too big and it bogs everything down when browsing on mobile or when on a tethered internet connection or whatever.

**Comment by narthur** [comment]
@dreeves Yes that's correct. Unfortunately I don't think the merged PR will fully address that on its own. I have a PR partway done for fixing the issue.
