### ISSUE TITLE
Fix heading alignment on mobile list pages

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#358]
```[tasklist]
### Desiderata
- [x] Fix it
- [x] Dreev confirms it looks good now
```

![Image](https://github.com/beeminder/blog/assets/4655422/14d1cfec-4f9d-4247-819c-8c6c0ba159c5)

_**Verbata**: alignment, css fussery,_

**Comment by dreeves** [comment]
Good catch!

**Comment by narthur** [comment]
This is fixed on month, year, tag, and author pages

**Comment by narthur** [comment]
@dreeves checkbox checked. Can we close now?
