### ISSUE TITLE
Lost embedded slideshow on triathlon post

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#359]
```[tasklist]
### Desiderata
- [x] NIX: See if Bee remembers anything about how it worked (unnecessary now; fully fixed!)
- [x] Dig up the actual images from the WordPress export?
- [x] Fix it
```

## Replicata 

1. Go to https://blog.beeminder.com/tri
2. See where it says "[slideshow id=1]"

## Expectata

To see a carousel slideshow thing of rotating images.

## Resultata

Just see something a slideshow in brackets.

## Nota Nebulosa

How the heck did that used to work on WordPress?

_**Verbata**: gallery of images, carousel, mendoza,_

**Comment by narthur** [comment]
I'm assuming these are the images that were in the slideshow:

![bethany_bike_tri](https://github.com/beeminder/blog/assets/4655422/6d29d382-8332-4f0d-ae55-945476123d0d)

![tridbik](https://github.com/beeminder/blog/assets/4655422/44068e29-95a3-4fae-a197-78e59a3e6932)

![tridrun](https://github.com/beeminder/blog/assets/4655422/b12d5251-1e36-45a3-9926-ada941ab500e)

![tridswm](https://github.com/beeminder/blog/assets/4655422/6e6aada5-9f6a-404f-9199-fac295ee8c2f)

**Comment by dreeves** [comment]
yes, but pretty sure there was also one of bee in the swim?

**Comment by narthur** [comment]
@dreeves I think this is done now: https://blog.beeminder.com/tri

**Comment by narthur** [comment]
@dreeves Do we still need @bsoule's input on this? Or can we go ahead and close as complete? I'm certain the old blog was using a WordPress plugin for these slideshows, given the slideshows were designated using shortcodes in the markdown.
