### ISSUE TITLE
Move sources file outside of repo

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#362]
```[tasklist]
### Desiderata
- [ ] Consensus in the comments
- [ ] TBD
```

This would allow us to go back to protecting the main branch. The sources file could be moved to an etherpad doc or a separate repo? Not sure what would be best. There might be a lightweight third-party tool along the lines of contentful or airtable or [strapi](https://strapi.io/) we could use that would make this all easier. Maybe even just a Google Sheet. If it was a Google Sheet, we could use Google Apps Script to trigger builds on sheet change.

## Cognata

* #318 

_**Verbata**: architecture, infra,_

**Comment by dreeves** [comment]
First naive question: are we sure we care about protecting master? 

But moving sources.json (as I think it should become) outside the repo does kinda make sense, I guess. I'd probably prefer Etherpad -- basically it'd be one of the source docs just like all the blog posts. It's just a meta source doc.

**Comment by dreeves** [comment]
(Reminder that I think sources.txt and wp-posts.csv should merge into a single big JSON document that contains -- directly or indirectly -- all the metadata for all the posts. (Containing the metadata for a blog post "indirectly" refers to the new current system where we point to the source doc URL for a blog post and the metadata for that blog post is at the top of its source doc.))

**Comment by narthur** [comment]
@dreeves I'm fine with punting on this.

**Comment by narthur** [comment]
Closing as nix for the time being.

**Comment by dreeves** [comment]
Snoozing would also be fine -- either way.
