### ISSUE TITLE
Fancy 404s and How WordPress Does It All Wrong

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#363]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Secretpreview link
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] Publish at https://blog.beeminder.com/antimagic404 on 2023-11-15
- [x] Blog blurbs
- [x] Waggledance
- [x] Tweet at https://x.com/bmndr/status/1732297843384500245 on 2023-12-05
- [x] NIX: Tip of the day
```

This started as a potential sidebar for the blogmorphosis post.

http://doc.bmndr.co/antimagic404

## Cognata

* #360 
* #320 
* https://blog.beeminder.com/404
* https://blog.beeminder.com/slytherin404

_**Verbata**: nerds, URL fetishism, URL fetishists,_

**Comment by dreeves** [comment]
![DALL·E 2023-11-15 21 38 36 - A cute and detailed image depicting cartoon-style bees examining the URL _beeminder com_ on digital screens  Each bee is directly facing and focusing ](https://github.com/beeminder/blog/assets/9928/1bb3a3ca-eb88-4778-b6bc-2730e865ea00)

**Comment by bsoule** [comment]
"These unix greybeards have atrocious spelling, no wonder they can't find the page they're looking for"

**Comment by dreeves** [comment]
![image](https://github.com/beeminder/blog/assets/9928/bb023598-bde2-4ef2-b907-66129ad5e105)

**Comment by dreeves** [comment]
![image](https://github.com/beeminder/blog/assets/9928/128b7545-75de-4b87-871c-b6b9fa8f1f49)
