### ISSUE TITLE
Fancy 404 page misunderstands slashes

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#364]
HT Michael LoPiccolo

## Replicata 

1. Navigate to https://blog.beeminder.com/control/foo
2. The 404 page correctly says 'Sad trombone. Here are things you might've meant: ... blog.beeminder.com/control'
3. Click it

## Expectata

That I get to blog.beeminder.com/control

## Resultata

It sends me to https://blog.beeminder.com/control/control (which 404s again)

_**Verbata**: URL parsing,_

**Comment by narthur** [comment]
Fixed with https://github.com/beeminder/blog/pull/410
