### ISSUE TITLE
Explicit disqus ID in metadata

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#372]
```[tasklist]
### Desiderata
- [x] Merge wp-posts.csv and sources.txt into sources.json
- [x] Compute disqus IDs for all old wordpress posts
- [x] Get the disqus IDs explicitly in the metadata
- [x] Get rid of the code that computed them
- [x] DRY up the "id" and "disqus_id" fields
```

## Cognata

* #327
* #318 

_**Verbata**: anti-magic, consistency, JSON metadata,_

**Comment by narthur** [comment]
this is done and deployed

**Comment by dreeves** [comment]
Can we clean up / DRY up these seemingly redundant fields in the legacy posts:

```
"id": "14",
"disqus_id": "14 https://blog.beeminder.com/?p=14",
```

I don't understand what's going on with those fields exactly but a space in the disqus ID shouldn't be allowed, right? It would be nice to have more sanity checks like breaking the build if a disqus ID is malformed and the above disqus ID sure looks malformed.

**Comment by narthur** [comment]
@dreeves Nope, spaces allowed. This is how the old blog did it, and we need to retain the exact same IDs to keep the link to their comments.

**Comment by dreeves** [comment]
Roger that. Gross but it's WordPress and Disqus's fault and nothing we can do now. What about getting rid of the "id" field? That's just the internal ID that WordPress used, right? Any possible value to keeping it?

**Comment by narthur** [comment]
@dreeves WordPress IDs removed: https://github.com/beeminder/blog/pull/407
