### ISSUE TITLE
Break the build if required metadata missing

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#380]
```[tasklist]
### Desiderata
- [x] First resolve #372
- [x] Narthur confirms that subsequent desiderata comprise the full list of metadata fields
- [x] Break the build if no slug
- [x] Break the build if no source
- [x] Break the build if no title
- [x] Break the build if no date
- [x] Break the build if no author
- [x] Break the build if no status
- [x] Break the build if no tags
- [x] Break the build if no disqus_id
- [x] Break the build if no excerpt
- [x] Break the build if no redirects
```

Proposal: All the metadata fields are required. If you really don't want to specify something, like a post should have no tags or whatever, then you should have to explicitly set it to "null" or the empty list.

One really nice thing about this: I wouldn't need to include all these things in the "publish the blog post" checklist. They'd all be self-enforcing.

## Cognata

* #372 
* #379 
* #377 
* #370

**Comment by dreeves** [comment]
And maybe for `excerpt` if you want it automatically extracted from the source doc you should have to say that explicitly? Like "excerpt": "MAGIC AUTO EXTRACT" (but with underscores)?

**Comment by narthur** [comment]
@dreeves Is the "give me a magic excerpt" feature something you're attached to? Or can we just require explicit excerpts for all non-legacy posts?

**Comment by dreeves** [comment]
I irrationally overthought this and finally came back to my comment above:

The `excerpt` field should be required and must always be a string. If that string is "MAGIC_AUTO_EXTRACT" then call [getExcerpt](https://github.com/beeminder/blog/blob/master/src/lib/getExcerpt.ts) to generate the excerpt.

[Magic strings are anti-magical](https://github.com/beeminder/blog/issues/212).

Rationale for wanting auto-extraction at all:

It's common for it to yield a good excerpt and it's nice and DRY -- if there's a typo fix in the first sentence of the post or something i don't need to make sure to fix it twice.

Rationale for not doing the obvious thing of auto-extracting if the excerpt field is missing:

Beyond the general anti-magic principle, I want to avoid having "pick an excerpt or vet the auto-excerpt" on my blog-publishing checklist. If everything's explicit then it's nice and self-enforcing.
