### ISSUE TITLE
Announcing the Readwise Reader Integration

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#381]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Secretpreview link
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] Publish at https://blog.beeminder.com/readwise on 2023-09-27
- [x] Blog blurbs
- [x] Waggledance
- [x] Tweet
- [x] Tip of the day
```

http://doc.bmndr.co/readwise

## Cognata

* #214 
* #282
* https://github.com/beeminder/totd/issues/44 

_**Verbata**: autodata integrations,_

**Comment by bsoule** [comment]
![cyberbeereader](https://github.com/beeminder/blog/assets/46881/610ee865-d1c3-49d4-aab0-611d8df01109)
