### ISSUE TITLE
Spurious greater-than signs in quoted, italicized text

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#385]
```[tasklist]
### Desiderata
- [ ] Diagnose the bug
- [ ] Decide whether to fix it or work around it
- [ ] TBD
```

We have a post -- https://blog.beeminder.com/olimay -- with the following markdown:

> *This is a guest post by 
> [Oliver Mayor](http://www.olimay.net/ "Known as olimay around the internet, including Beeminder"), 
> an avid Beeminder user for going on four years.
> He's a software developer who's interested in human-behavior-shaping technology and often has pretty deep insights related to Beeminder.
> We were especially impressed with his thoughts on the different modes of beeminding (and the black vs yellow characterization) and asked if he'd like to expand on it here, along with some of the story of his own Beeminder journey.
> We're still thinking about what this means for how Beeminder should present itself to new users, and in terms of the new 
> [premium plans](http://blog.beeminder.com/infinibee "Previous post introducing the changes to premium plans"),
> which could be seen as paving the way for more emphasis on Team Yellow.*

That generates the following in production:

![image](https://github.com/beeminder/blog/assets/9928/b7ea2791-6ccf-48fc-86b4-8314714a2b19)

(Note the spurious `>` symbols.)

It's correct in the expost rendering:

![image](https://github.com/beeminder/blog/assets/9928/ce69acda-78ab-4b07-8c8c-a2dc316f34e0)

I'm now working around this on the /olimay post but we need to hunt down other instances of this fairly urgently.

## Cognata

* #376 

_**Verbata**: typographical errors, markdown rendering bugs,_

**Comment by dreeves** [comment]
Note also that it works in GitHub's Markdown, modulo the newlines, which is a known difference in the flavor of Markdown we use vs GitHub-flavored Markdown.

**Comment by dreeves** [comment]
Crap, there might be a lot of these. Just started clicking through and quickly found another one from the same era:

https://blog.beeminder.com/arbeetrary

**Comment by narthur** [comment]
@dreeves It looks fixed now. Did you add a workaround? Otherwise I think this was caused by my poor Friday fix that I reverted.

**Comment by dreeves** [comment]
Ha, yeah, I did the workaround for /olimay at the time but no others. So I agree that this is fixed now and the workaround would not have been necessary! Phew!
