### ISSUE TITLE
More line spacing

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#386]
```[tasklist]
### Desiderata
- [x] Bump up the line spacing
- [x] Point to this gissue in one of the gissues in the cognata about doing something more general
```

I'm just now realizing that the line spacing seems too squished:

![image](https://github.com/beeminder/blog/assets/9928/85fae2e7-9bac-4d90-960f-12fe3b1d747d)

Compare with Substack:

![image](https://github.com/beeminder/blog/assets/9928/9b381473-58f4-421a-b1fe-8e0565c3bde3)

I could be wrong -- I don't trust my aesthetic sense. But what are, like, best practices for this kind of thing?

## Cognata

* #385
* #316
* #355

_**Verbata**: css, typography,_

**Comment by dreeves** [comment]
More generally, how do we avoid whack-a-moling these things? Is there something off-the-shelf, so to speak, we can use for all these kinds of typographical decisions?

**Comment by narthur** [comment]
This should be fixed now!

**Comment by dreeves** [comment]
Looks so much nicer! Thank you! Funny that it took me so long to notice that. Which... I guess brings me back to my whack-a-mole question and whether there's some way to borrow a bunch of CSS wholesale from some place like Substack or the New York Times or something who will have put a ton of thought into questions like this.

**Comment by narthur** [comment]
@dreeves Frankly it's not at all clear to me which direction would be less work. Not opposed to exploring the idea, though. I've created an issue for that here: https://github.com/beeminder/blog/issues/404
