### ISSUE TITLE
Special case for prev/next links on initial post

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#388]
```[tasklist]
### Desiderata
- [x] Narthur opines on whether it's a simple fix or if it may involve hacking Astro or something
- [x] Deploy fix
```

## Replicata 

1. Go to https://blog.beeminder.com/akrasia
2. Look at the prev/next links at the top

## Expectata

Like this, with previous on the left and next on the right:

![image](https://github.com/beeminder/blog/assets/9928/7e7839bc-1012-4a58-b8f4-3c6a95de14c8)

## Resultata

Next is on the left!

![image](https://github.com/beeminder/blog/assets/9928/dbc2a1f5-813b-46b3-b8ab-9d62ea1a624f)

## Nota Nebulosa

Pretty minor, but is kinda legit confusing if you're flipping through one by one and hit the inaugural post!

_**Verbata**: prev/next navigation, links to next and previous posts, bitty bugs,_

**Comment by dreeves** [comment]
If it were easier we could have what would normally be the prev link be the static text "(Inaugural post!)"

**Comment by narthur** [comment]
This is fixed
