### ISSUE TITLE
Lists broken on tons of old posts!

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#389]
```[tasklist]
### Desiderata
- [x] Fix it
- [x] Postmortem from narthur (see #387)
- [x] Review more of these until we're sure everything's fixed
```

HT Paul Schmidt who tabulated blog posts up through https://blog.beeminder.com/anomalily (which is as far as he's read so far) that have problems with block quotes and/or unordered/ordered lists:

- [x] https://blog.beeminder.com/gym (the Further Reading section doesn't have the "ul" elements on separate lines)
- [x] https://blog.beeminder.com/unintended
- [x] https://blog.beeminder.com/backfiring
- [x] https://blog.beeminder.com/dial
- [x] https://blog.beeminder.com/beenamer (not sure if the Kibitzer definition section counts or not, but also the "let us count the ways" enumeration ("ol") runs together for numbers 2-6)
- [x] https://blog.beeminder.com/launch
- [x] https://blog.beeminder.com/wantcanwill (no block quote problem, but "want-can-will test" has "ol" running together)
- [x] https://blog.beeminder.com/trackhack ("ul" list of websites all on the same line)
- [x] https://blog.beeminder.com/competitors ("ul" problem throughout, and block quote problem in the footnotes)
- [x] https://blog.beeminder.com/gandalf
- [x] https://blog.beeminder.com/monkey ("ul" problem only)
- [x] https://blog.beeminder.com/innocentive ("list of real-world commitment devices" and "further reading" sections have "ol" that runs together, block quote problem only in the footnotes)
- [x] https://blog.beeminder.com/weasels (subtle "ul" problem ("nub of it"))
- [x] https://blog.beeminder.com/buzz ("roundup items" "ul" problem)
- [x] https://blog.beeminder.com/synonyms (also "ul" problem in two sections)
- [x] https://blog.beeminder.com/perverse
- [x] https://blog.beeminder.com/api ("ul" problem in a few places)
- [x] https://blog.beeminder.com/habits
- [x] https://blog.beeminder.com/gmailzero
- [x] https://blog.beeminder.com/mustdo
- [x] https://blog.beeminder.com/one ("ul" problem only)
- [x] https://blog.beeminder.com/apps (spacing of the text between the screenshots is weird)
- [x] https://blog.beeminder.com/nanowrimo
- [x] https://blog.beeminder.com/shortcircuit ("ol" problem after "three constraints")
- [x] https://blog.beeminder.com/southwest ("ul" run-ons)
- [x] https://blog.beeminder.com/gratitude ("ul" in two places)
- [x] https://blog.beeminder.com/recommit ("ol")
- [x] https://blog.beeminder.com/box (plus "ul" in "addendum")
- [x] https://blog.beeminder.com/legit ("ol")
- [x] https://blog.beeminder.com/premium ("ol" - multiple)
- [x] https://blog.beeminder.com/wsj ("ul")
- [x] https://blog.beeminder.com/zeno (in footnotes)
- [x] https://blog.beeminder.com/nick (also "ul")
- [x] https://blog.beeminder.com/curtain (in "what not to do" section, x 2)
- [x] https://blog.beeminder.com/nwo ("ol")
- [x] https://blog.beeminder.com/cheating ("ol")
- [x] https://blog.beeminder.com/uvi ("ul" in body, also in "related" at bottom)
- [x] https://blog.beeminder.com/beedroid ("ul" in "other goodies")
- [x] https://blog.beeminder.com/bikes (2 places)
- [x] https://blog.beeminder.com/dip (also "ul" in a few places)
- [x] https://blog.beeminder.com/beekeeper (also "ul" and "ol")
- [x] https://blog.beeminder.com/beenice
- [x] https://blog.beeminder.com/runnersworld ("ul")
- [x] https://blog.beeminder.com/codeschool
- [x] https://blog.beeminder.com/fatty (also "ul")
- [x] https://blog.beeminder.com/vegetables (also "ul" in "further reading")
- [x] https://blog.beeminder.com/supporters
- [x] https://blog.beeminder.com/comfortzone (also "ul")
- [x] https://blog.beeminder.com/hieroglyphs (also has a few "ol", and broken markdown links issues in several sections)
- [x] https://blog.beeminder.com/maniac ("ul" in footnotes)
- [x] https://blog.beeminder.com/exproad (no copy issues, but the header pic makes me want to go do the Hilly Hundred!)
- [x] https://blog.beeminder.com/fatcyclist (intro)
- [x] https://blog.beeminder.com/philip (also some markdown links issues)
- [x] https://blog.beeminder.com/typebee ("ol")
- [x] https://blog.beeminder.com/twitter
- [x] https://blog.beeminder.com/smarmbot
- [x] https://blog.beeminder.com/buzz5 ("ol" - 2 sections)
- [x] https://blog.beeminder.com/discourse (also "ul")
- [x] https://blog.beeminder.com/habitrpg
- [x] https://blog.beeminder.com/three (also "ol")
- [x] https://blog.beeminder.com/deadlines ("ol" in "known issues")
- [x] https://blog.beeminder.com/zapier
- [x] https://blog.beeminder.com/veggieminding (multiple places)
- [x] https://blog.beeminder.com/rituals (also in footnotes)
- [x] https://blog.beeminder.com/rosary (multiple places, also code formatting should be in code blocks)
- [x] https://blog.beeminder.com/sleep
- [x] https://blog.beeminder.com/bucket (when Bee wrested the keyboard from you)
- [x] https://blog.beeminder.com/epson
- [x] https://blog.beeminder.com/triangle (also "ol")
- [x] https://blog.beeminder.com/garmin
- [x] https://blog.beeminder.com/movingav
- [x] https://blog.beeminder.com/beeyond (multiple places)
- [x] https://blog.beeminder.com/fearofbees
- [x] https://blog.beeminder.com/crisis
- [x] https://blog.beeminder.com/gmailzeroer ("ol" in first footnote)
- [x] https://blog.beeminder.com/ifttt
- [x] https://blog.beeminder.com/smoking (not sure if these intro ones count, but also block quote problem in the aside, and "ul" right after that)
- [x] https://blog.beeminder.com/skritter
- [x] https://blog.beeminder.com/qs15 ("ol" in the journal entries)
- [x] https://blog.beeminder.com/nudge ("ol")
- [x] https://blog.beeminder.com/chelsea
- [x] https://blog.beeminder.com/mirabai
- [x] https://blog.beeminder.com/trust (also "ul" in footnotes)
- [x] https://blog.beeminder.com/should ("ul")
- [x] https://blog.beeminder.com/qs2015 (also "ol" in "Pomodoros" section)
- [x] https://blog.beeminder.com/buzzyear ("ul" and "ol")
- [x] https://blog.beeminder.com/reminders ("ul" and "ol")
- [x] https://blog.beeminder.com/waterfalls
- [x] https://blog.beeminder.com/four (block quote and/or ol problem in "flashback")
- [x] https://blog.beeminder.com/complice (also "ul" in "current integration features" and "social productivity" sections)
- [x] https://blog.beeminder.com/faire
- [x] https://blog.beeminder.com/systems
- [x] https://blog.beeminder.com/buzz7 ("ol")
- [x] https://blog.beeminder.com/habitica (and "ul")
- [x] https://blog.beeminder.com/frictionless ("ul" in a few places)
- [x] https://blog.beeminder.com/mongoid ("ol")
- [x] https://blog.beeminder.com/ego
- [x] https://blog.beeminder.com/willpower ("ol")
- [x] https://blog.beeminder.com/deathtofreebees (in body and footnote)
- [x] https://blog.beeminder.com/custard
- [x] https://blog.beeminder.com/creditcard ("ol" x 2)
- [x] https://blog.beeminder.com/buzz9 ("ol")
- [x] https://blog.beeminder.com/road ("ol")
- [x] https://blog.beeminder.com/beemplice ("ul")
- [x] https://blog.beeminder.com/arbeetrary
- [x] https://blog.beeminder.com/infinibee ("ul" in multiple sections)
- [x] https://blog.beeminder.com/olimay (intro is fixed, but same problem in "two paths for Beeminder success" section. also "ul" in "Beeminder without penalties" section above that)
- [x] https://blog.beeminder.com/anomalily (also "ul")

> Phew! That brings me up to my current place in the beeblog. I think I had mentally blocked those kinds of problems out in the beginning, chalking it up to new blog system rollout issues, but if these require manual fixing, I'll continue to point them out. (Let me know if it's fixed systemically/programmatically though, and I won't bother)

## Cognata

* #387 
* https://github.com/beeminder/blog/commit/007ef20018bf139108db2a5cc3fd01696b8f3f0e

_**Verbata**: mega-gissue, regressions,_

**Comment by narthur** [comment]
confirmed broken markdown links: https://blog.beeminder.com/beekeeper
