### ISSUE TITLE
Disqus thinks posts have "DRAFT: " prepended to the title

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#391]
```[tasklist]
### Desiderata
- [x] Deploy fix
- [x] NIX: Narthur gives postmortem and/or links to previous discussion
- [x] Dreev confirms it's fixed next time he gets a notification from Disqus on a new post
```

I think there's already a gissue about this but I can't find it. When Disqus emails me about new comments, it refers to, for example, the latest post as "DRAFT: Beeminder ♥ Readwise Reader".

Presumably that's not just admins but also users who see that in Disqus's interface? (Again, I think you answered this before but I can't find where.)

## Cognata

* #396 

_**Verbata**: disqus comments, magically prepend "draft" to post titles,_

**Comment by narthur** [comment]
This should be fixed now.

**Comment by dreeves** [comment]
Do you remember the previous discussion about this? Maybe that was in Slack or something? (Or I'm crazy, of course.)

**Comment by narthur** [comment]
@dreeves No, I don't recall where we discussed this previously.
