### ISSUE TITLE
Font mishmash in post body

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#392]
```[tasklist]
### Desiderata
- [x] Narthur reminds us about the last time we saw something like this (related gissues now collected)
- [x] Deploy fix
```

## Replicata 

1. Go to https://blog.beeminder.com/weasels on desktop

## Expectata

That the body font is consistent.

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/ab5214a2-aace-446a-b7b7-2babed4f86a4)

## Cognata

* #297 
* #355
* #404

_**Verbata**: mendoza, css, font problems, typesetting,_

**Comment by narthur** [comment]
@dreeves This is fixed

**Comment by dreeves** [comment]
(General request to have the PR or commit mention the gissue it's addressing.)

What's the postmortem on this one? I'm worried about whack-a-mole with weird css things like this and wondering if there's a way to make things more robust. Speaking of which, it may make sense to move this discussion to #355.

**Comment by narthur** [comment]
@dreeves Good call. I'm not sure #355 is the best place. Here's a perhaps better issue:

https://github.com/beeminder/blog/issues/404
