### ISSUE TITLE
Does the canonical URL have a trailing slash or not?

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#394]
```[tasklist]
### Desiderata
- [x] Discuss severity, eg, does Google penalize for this?
- [x] Add rel-canonical thing
- [x] Add redirects? (not necessary, we'll assume)
```

This sounds like the kind of thing that might be important for SEO, or I guess just for tidiness?

## Replicata

1. Surf to https://blog.beeminder.com/foo (where "foo" is any valid slug, though also works for invalid slugs)
2. Surf to https://blog.beeminder.com/foo/ (same thing but with trailing slash)
3. Surf to https://blog.beeminder.com/foo// (two or any number of trailing slashes)
4. Surf to https://blog.beeminder.com/foo/index
5. Surf to https://blog.beeminder.com/foo/index.html

## Expectata

To be redirected to whatever the canonical version is.

## Resultata

No redirection. We essentially have multiple URLs all with identical content.

## Cognata

* #364 

_**Verbata**: SEO, rel-canonical, canonical URLs, legacy redirects,_

**Comment by narthur** [comment]
@dreeves I just checked `foodhabits` for all those examples. Double-slash 404'd for me. Every other variant had the canonical URL attribute in the HTML head set to `https://blog.beeminder.com/foodhabits/` so I think we're good on SEO.
