### ISSUE TITLE
Excerpt auto-extract broken!

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#413]
![image](https://github.com/beeminder/blog/assets/9928/ddf373fd-8815-4597-856b-5ffc1c44ecd6)

**Comment by narthur** [comment]
@dreeves That would be because we haven't deployed that feature yet! I'm about to deploy it right now.

**Comment by narthur** [comment]
@dreeves Did a bit more digging, and this one was my fault. We got a bit ahead of ourselves on the deploy here. It should be fixed with #415 though.
