### ISSUE TITLE
Raw html/unicode/markdown appearing in excerpts

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#419]
```[tasklist]
### Desiderata
- [x] Narthur opines
- [x] Deploy fix
```

## Replicata

1. Go to https://blog.beeminder.com/tags/buzz
2. Look at top post in the list

## Expectata

That I see a readable excerpt.

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/f72400f4-e01a-49ed-a645-aa5b81c89a60)

## Nota Nebulosa

Maybe the fault of the auto-extractor?

## Cognata

* #416 (sounds related?)
* #420

_**Verbata**: excerpts, blurbs, raw unicode, typography bugs, raw markdown,_

**Comment by dreeves** [comment]
It's worse than I thought:

![image](https://github.com/beeminder/blog/assets/9928/3a9d1307-3527-43e0-b943-18f57c9a9e39)

From https://blog.beeminder.com/2014/March

**Comment by narthur** [comment]
The HTML entities issue is fixed with https://github.com/beeminder/blog/pull/420. We're still figuring out the raw Markdown link issue.

**Comment by narthur** [comment]
It looked like the raw markdown link issue was a typo in the markdown along these lines:

`[text](https://example.com ""the alt text"")`

The extra set of quotes is now removed, so this issue should be resolved.
