### ISSUE TITLE
Announcing the Manifold Autodata Integration

### ISSUE THREAD

**Issue by bsoule** [beeminder/blog#451]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Secretpreview link
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] Publish at https://blog.beeminder.com/manifold
- [x] Blog blurbs
- [x] Waggledance
- [x] Tweet
- [x] NIX: Tip of the day
```

## Cognata

* https://github.com/beeminder/beeminder/issues/4537

_**Verbata**: prediction markets, manifold markets, autodata integrations, feature announcements,_

**Comment by dreeves** [comment]
![DALL·E 2023-10-29 22 48 14 - Photo of a charming anime-style bee with big, sparkling eyes, riding on the back of a beautifully folded origami crane  The crane gracefully soars thr](https://github.com/beeminder/blog/assets/9928/2e682836-57ab-4fd8-a298-78b8d16a956f)

**Comment by bsoule** [comment]
<img width="406" alt="manifold_username" src="https://github.com/beeminder/blog/assets/46881/8f196dc7-3562-4091-aab4-6b391feb664c">

<img width="416" alt="manifold_goal_setup" src="https://github.com/beeminder/blog/assets/46881/6fcd760d-d969-4cfd-81d4-4bdf0e58e189">

<img width="1069" alt="manifold_goal" src="https://github.com/beeminder/blog/assets/46881/a4fde0cf-f34f-488b-bcc6-c8c50b2cc360">

<img width="458" alt="Screen Shot 2023-11-02 at 01 31 54" src="https://github.com/beeminder/blog/assets/46881/fe6ced5a-00b8-46e9-a7be-4bc6906594c6">

**Comment by bsoule** [comment]
<img width="374" alt="Screen Shot 2023-11-02 at 02 10 25" src="https://github.com/beeminder/blog/assets/46881/33e20ae8-bf29-4504-85fe-7f607d3e7489">
<img width="1064" alt="Screen Shot 2023-11-02 at 02 14 00" src="https://github.com/beeminder/blog/assets/46881/1781d0df-cbde-4dca-974c-b5334b2b4917">
