### ISSUE TITLE
Beeminder Featured on Humble Bundle!

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#468]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] Publish
- [x] Blog blurbs
- [x] Waggledance
- [x] Tweet
- [x] NIX: Tip of the day
```

_**Verbata**: promotions, humblebundle, humbee, honey money, honeymoney,_

**Comment by dreeves** [comment]
![humbee-dall-e](https://github.com/beeminder/blog/assets/9928/026a125d-90ad-4f1c-aa58-bfe2e38f2910)

**Comment by bsoule** [comment]
this is not the final draft, but it's pretty close:

![Screen Shot 2024-02-08 at 11 46 10](https://github.com/beeminder/blog/assets/46881/4c560bbf-1be4-453f-b2af-8d70a1d851df)

**Comment by bsoule** [comment]
<img width="711" alt="Screen Shot 2024-02-28 at 20 24 36" src="https://github.com/beeminder/blog/assets/46881/4bf7a707-23e0-40e3-9ff3-3fad601e1d07">
