### ISSUE TITLE
Footnotes should be able to end with a number

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#470]
```[tasklist]
### Desiderata
- [x] Fix it on 2024-03-07
- [x] Tweet UVI on 2024-03-08
```

Compare:
https://blog.beeminder.com/sediment
https://doc.bmndr.co/sediment

See how the footnote is misrendered in the blog version:

<img width="118" alt="image" src="https://github.com/beeminder/blog/assets/9928/1f7a1d98-ecbb-4e8e-9635-3009cb567d6b">

Probably this is a simple regex tweak? Like footnote tags should be `/[a-z]\w*/i` or similar.

## Cognata

* http://beeminder.com/changelog#4806 (UVI)

_**Verbata**: zombie, regression, custom markdown,_

**Comment by narthur** [comment]
@dreeves This should be fixed with #471.
