### ISSUE TITLE
Death to Zero Dollar Goals, Birth of Feet-Wetting Mode

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#490]
```[tasklist]
### Desiderata
- [x] Have someone read a draft
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] Publish at https://blog.beeminder.com/wetfeet on 2024-05-01
- [x] Blog blurbs
- [x] Waggledance
- [x] Tweeted at https://x.com/beemuvi/status/1785079458279629127
- [x] NIX: Tip of the day
- [x] NIX: Anki the URL?
```

## Cognata

* http://doc.bmndr.co/deathtozero
* http://beeminder.com/changelog#4857 (tweeted but still in staging...)
* https://github.com/beeminder/beeminder/issues/4837

_**Verbata**: feature announcements, feature unannouncements, death to pledgeless goals,_

**Comment by bsoule** [comment]
<img width="337" alt="Checkbox which says 'Hold the pledge at $0 for 7 days while I get my feet wet'" src="https://github.com/beeminder/blog/assets/46881/9416c485-7c73-4762-a1ee-d9455d7e3893">
<img width="383" alt="A notice to Beemium users mentioning that they can still hold at $0 with a $0 pledge cap" src="https://github.com/beeminder/blog/assets/46881/0a556319-7aba-4823-83d1-2f61271bb8ea">
<img width="387" alt="the full pledge stack from $0 -> $0 pledge cap for a Beemium user" src="https://github.com/beeminder/blog/assets/46881/1b99a350-f45e-4596-adce-2c02dcdfed72">

**Comment by bsoule** [comment]
![bethany4036_wet_feet_in_a_pool_of_money_7bd17d6a-0056-4687-b57e-183d813c09d9](https://github.com/beeminder/blog/assets/46881/d9164fb4-fb47-4ec6-97cf-cca9c8ffde0a)

**Comment by bsoule** [comment]
![wet_money_feet](https://github.com/beeminder/blog/assets/46881/82eecb6f-48a5-49cb-91a9-8ac9bddc90d4)

**Comment by bsoule** [comment]
<img width="376" alt="Screenshot 2024-05-01 at 22 37 54" src="https://github.com/beeminder/blog/assets/46881/f0f9d833-d2ae-4730-9a24-bc61f28b3f33">

**Comment by bsoule** [comment]
<img width="398" alt="Screenshot 2024-05-01 at 22 45 31" src="https://github.com/beeminder/blog/assets/46881/f4659be5-cd6f-46e1-8206-47d73fdfbcdc">
